# Generated by Django 5.0.3 on 2024-03-10 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_message_fromuser_remove_message_touser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touser',
            name='user',
        ),
        migrations.DeleteModel(
            name='FromUser',
        ),
        migrations.DeleteModel(
            name='ToUser',
        ),
    ]
