# Generated by Django 5.0.3 on 2024-03-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='created',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='message',
            name='updated',
        ),
        migrations.AddField(
            model_name='message',
            name='thread_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
