# Generated by Django 5.0.3 on 2024-03-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_created_message_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='online_status',
            field=models.BooleanField(default=False),
        ),
    ]
